AspNetCoreMvc_Proje_WebMvc/Controllers/AnaSayfaController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_Proje_WebMvc.Controllers
{
    public class AnaSayfaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetCoreMvc_Proje_WebMvc/Controllers/CartController.cs
using AspNetCoreMvc_Proje_Entity.Entities;
using AspNetCoreMvc_Proje_Entity.Services;
using AspNetCoreMvc_Proje_Entity.ViewModels;
using AspNetCoreMvc_Proje_WebMvc.SessionExtensions;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_Proje_WebMvc.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICartLineService _cartLineService;

        public CartController(IProductService productService, ICartLineService cartLineService)
        {
            _productService = productService;
            _cartLineService = cartLineService;
        }
        List<CartLineViewModel> Cart;


        public IActionResult Index()
        {
            Cart = GetCart();
            ViewBag.total = _cartLineService.TotalPrince(Cart);
            return View(Cart);
        }
        public void AddCart(int id,int quantity)
        {
            Cart = GetCart();
            Cart = _cartLineService.AddCart(Cart,id,quantity);
            SaveCart(Cart);
        }
        public List<CartLineViewModel> GetCart()
        {
            var cart = HttpContext.Session.GetJson<List<CartLineViewModel>>("cart") ?? new List<CartLineViewModel>();
            return cart;
        }
        public IActionResult DeleteCart(int id)
        {
            Cart = GetCart();
            Cart = _cartLineService.RemoveCart(Cart, id);
            SaveCart(Cart);
            return RedirectToAction("Index");
        }
        public void SaveCart(List<CartLineViewModel> cartline)
        {
            HttpContext.Session.SetJson("cart", cartline);
        }
        public IActionResult DropdownRefresh()
        {
            Cart = GetCart();
            ViewBag.total = _cartLineService.TotalPrince(Cart);
            return ViewComponent("CartDropdown", Cart);
        }
        public IActionResult CartCount()
        {
            int count = GetCart().Count();
            return ViewComponent("CartCount",count);
        }
    }
}

AspNetCoreMvc_Proje_WebMvc/Controllers/UrunlerController.cs
using AspNetCoreMvc_Proje_Entity.ViewModels;
using AspNetCoreMvc_Proje_Entity.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AspNetCoreMvc_Proje_Entity.Entities;

namespace AspNetCoreMvc_Proje_WebMvc.Controllers
{
    public class UrunlerController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductSpecsService _productSpecsService;
        private readonly IMapper _mapper;
        private readonly IFilterSpecService _filterSpecService;

        public UrunlerController(IProductService productService, IMapper mapper, IProductSpecsService productSpecsService, IFilterSpecService filterSpecService)
        {
            _productService = productService;
            _mapper = mapper;
            _productSpecsService = productSpecsService;
            _filterSpecService = filterSpecService;
        }

        public IActionResult Index(int? id, string[]? value)
        {
            

            var products = _productService.GetListAllByFilter(x => x.Status == true && x.CategoryId == id);
            
            if (value.Count() > 0)
            {
                var specs = _productSpecsService.GetAll();
                List<Products> list = new List<Products>();
                foreach (var item in value)
                {
                    foreach (var spec in specs)
                    {
                        if (spec.Value == item)
                        {
                            //list.Add(products.Where(x => x.Id == spec.ProductId).FirstOrDefault());
                        }
                    }
                }
                ViewBag.specs = _filterSpecService.GetListAllByFilter(x => x.CategoryId == id);
                return View(_mapper.Map<List<ProductViewModel>>(list));
            }



            ViewBag.specs = _filterSpecService.GetListAllByFilter(x => x.CategoryId == id);
            return View(_mapper.Map<List<ProductViewModel>>(products));
        }
    }
}

AspNetCoreMvc_Proje_WebMvc/ViewComponents/CartCount/CartCountViewComponent.cs
using AspNetCoreMvc_Proje_Entity.ViewModels;
using AspNetCoreMvc_Proje_WebMvc.SessionExtensions;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_Proje_WebMvc.ViewComponents.CartCount
{
    public class CartCountViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var cart = HttpContext.Session.GetJson<List<CartLineViewModel>>("cart") ?? new List<CartLineViewModel>();
            return View(cart.Count());
        }
    }
}

AspNetCoreMvc_Proje_WebMvc/Views/Shared/LayoutFooterPartial.cshtml
<footer class="footer">

    <div class="footer-middle bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3">
                    <div class="widget widget-about text-white">
                        <img src="~/proje/assets/images/demos/demo-4/logo-footer.png" class="footer-logo" alt="Footer Logo" width="105" height="25">
                        <p class="text-white">
                            Türkiye'nin en büyük online alışveriş sitesi Siteİsmi, 2023 yılından bu yana hizmet veriyor. Siteİsmi, yenilikleri ile Türkiye'nin dijital alışveriş sektörüne yön veriyor.
                        </p>

                        <div class="widget-call">
                            <i class="icon-phone"></i>
                            Aklınıza takılan bir soru mu var?
                            <a href="tel:#">+0123 456 789</a>
                        </div><!-- End .widget-call -->
                    </div><!-- End .widget about-widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title text-white">Kurumsal</h4><!-- End .widget-title -->

                        <ul class="widget-list text-white">
                            <li><a href="about.html">Siteİsmi Hakkında</a></li>
                            <li><a href="#">Hizmetlerimiz</a></li>
                            <li><a href="#">Kişisel Verilerin Korunması</a></li>
                            <li><a href="faq.html">S.S.S</a></li>
                            <li><a href="contact.html">İletişim</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title text-white">Müşteri Hizmetleri</h4><!-- End .widget-title -->

                        <ul class="widget-list text-white">
                            <li><a href="#">Ödeme Yöntemleri</a></li>
                            <li><a href="#">Satın alınan ürünle ilgili talepler</a></li>
                            <li><a href="#">İptal ve iade</a></li>
                            <li><a href="#">Teslimat ve kargo</a></li>
                            <li><a href="#">Güvenli Alışveriş Kılavuzu</a></li>
                            <li><a href="#">Bilgi Güvenliği Politikası</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title text-white">Hesabım</h4><!-- End .widget-title -->

                        <ul class="widget-list text-white">
                            <li><a href="#">Giriş Yap</a></li>
                            <li><a href="cart.html">Sepeti Görüntüle</a></li>
                            <li><a href="#">Favoriler</a></li>
                            <li><a href="#">Siparişlerim</a></li>
                            <li><a href="#">Yardım</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .footer-middle -->

    <div class="footer-bottom">
        <div class="container">
            <p class="footer-copyright">Copyright © 2019 Molla Store. All Rights Reserved.</p><!-- End .footer-copyright -->
            <figure class="footer-payments">
                <img src="~/proje/assets/images/payments.png" alt="Payment methods" width="272" height="20">
            </figure><!-- End .footer-payments -->
        </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer>

AspNetCoreMvc_Proje_WebMvc/Views/Shared/LayoutHeaderPartial.cshtml
<header class="header header-intro-clearance header-4">


    <div class="header-middle">
        <div class="container">
            <div class="header-left">
                <button class="mobile-menu-toggler">
                    <span class="sr-only">Toggle mobile menu</span>
                    <i class="icon-bars"></i>
                </button>

                <a asp-action="Index" asp-controller="AnaSayfa" class="logo">
                    <img src="~/proje/assets/images/demos/demo-4/logo.png" alt="Molla Logo" width="105" height="25">
                </a>
            </div><!-- End .header-left -->

            <div class="header-center">
                <div class="header-search header-search-extended header-search-visible d-none d-lg-block">
                    <a href="#" class="search-toggle" role="button"><i class="icon-search"></i></a>
                    <form action="#" method="get">
                        <div class="header-search-wrapper search-wrapper-wide">
                            <label for="q" class="sr-only">Search</label>
                            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
                            <input type="search" class="form-control" name="q" id="q" placeholder="Ürün Ara..." required>
                        </div><!-- End .header-search-wrapper -->
                    </form>
                </div><!-- End .header-search -->
            </div>

            <div class="header-right">

                <div class="wishlist">
                    <a href="wishlist.html" title="Wishlist">
                        <div class="icon">
                            <i class="icon-heart-o"></i>
                            <span class="wishlist-count badge">3</span>
                        </div>
                        <p>Favoriler</p>
                    </a>
                </div><!-- End .compare-dropdown -->

                <div class="dropdown cart-dropdown">
                    <a asp-action="Index" asp-controller="Cart" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                        <div class="icon">
                            <i class="icon-shopping-cart"></i>
                            <span class="cart-count"><vc:cart-count></vc:cart-count></span>
                        </div>
                        <p>Sepet</p>
                    </a>

                    <vc:cart-dropdown></vc:cart-dropdown>
                </div><!-- End .cart-dropdown -->
                <div class="wishlist">
                    <a href="#signin-modal" title="Giriş Yap" data-toggle="modal">
                        <div class="icon">
                            <i class="icon-user"></i>
                        </div>
                        <p>Giriş Yap</p>
                    </a>
                </div>
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-middle -->

    <div class="header-bottom sticky-header">
        <div class="container">
            <div class="header-left">
                <div class="dropdown category-dropdown">
                    <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static" title="Browse Categories">
                        Tüm Kategoriler <i class="icon-angle-down"></i>
                    </a>

                    <div class="dropdown-menu">
                        <nav class="side-nav">
                            <ul class="menu-vertical sf-arrows">
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="7">Masaüstü Bilgisayar</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="6">Laptop</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="1">Telefon</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="2">Tablet</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="3">Televizyon</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="4">Oyun Konsolu</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="10">Yazıcı</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="5">Kamera</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="8">Isıtıcı</a></li>
                                <li class="item-lead"><a asp-action="Index" asp-controller="Urunler" asp-route-id="9">Klima</a></li>
                            </ul><!-- End .menu-vertical -->
                        </nav><!-- End .side-nav -->
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .category-dropdown -->
            </div><!-- End .header-left -->

            <div class="header-center">
                <nav class="main-nav">
                    <ul class="menu sf-arrows">
                        <li class="megamenu-container mx-3">
                            <a href="index.html">Ana Sayfa</a>
                        </li>
                        <li class="mx-3">
                            <a href="category.html">Shop</a>
                        </li>
                        <li class="mx-3">
                            <a href="product.html">Product</a>
                        </li>
                        <li class="mx-3">
                            <a href="#">Pages</a>
                        </li>
                        <li>
                            <a href="blog.html">Hakkımızda</a>
                        </li>
                        <li class="mx-3">
                            <a href="elements-list.html">İletişim</a>
                        </li>
                    </ul><!-- End .menu -->
                </nav><!-- End .main-nav -->
            </div><!-- End .header-center -->

            <div class="header-right">
                <i class="la la-lightbulb-o"></i><p><span class="highlight">İlk Siparişinizde&nbsp30% İndirim</span></p>
            </div>
        </div><!-- End .container -->
    </div><!-- End .header-bottom -->
</header>

AspNetCoreMvc_Proje_WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreMvc_Proje_WebMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetCoreMvc_Proje_WebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreMvc_Proje_WebMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspNetCoreMvc_Proje_WebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>